### ISSUE TITLE
Yaw

### ISSUE THREAD

**Issue by Lelelo1** [dpyeates/react-native-attitude#1]
First of all thanks for creating this library.

I came here looking for yaw. As I understand it it is being calculated but is just not exposed for usage. So I did expose it - and commented out roll and pitch in sendEventWithName. However moving my device by roll and pitch slightly - changes yaw drastically. Having the device on a table why is that?

**Comment by andresrabinovich** [comment]
Same thing happened to me, fixed it changing line:
*yaw   = atan2f(2.0f * adbc, 1.0f - 2.0f * (z2 + x2)) * RADTODEG;
to:
*yaw   = atan2f(2.0*(q.y*q.z + q.w*q.x), q.w*q.w - q.x*q.x - q.y*q.y + q.z*q.z) * RADTODEG;
Of course, you also have to expose yaw and do the rest.
(the fixed formula came from https://stackoverflow.com/questions/5782658/extracting-yaw-from-a-quaternion)

**Comment by Lelelo1** [comment]
I [found](https://stackoverflow.com/questions/56005107/roll-pitch-and-yaw-interdependence) I could also simply grab roll, pitch and yaw directly from [cmdevicemotion](https://developer.apple.com/documentation/coremotion/cmdevicemotion) and there was no problem. (on iOS)
