### ISSUE TITLE
null is not an object (evaluating 'RNAttitude.startObserving')

### ISSUE THREAD

**Issue by nkulic** [dpyeates/react-native-attitude#2]
After installing library I've imported to my project: 
`import Attitude from 'react-native-attitude';`

And error is hit when running the following code: 
`  Attitude.watch((payload) => {
    console.log(
      '\nRoll: ' +
        payload.roll +
        '\nPitch: ' +
        payload.pitch +
        '\nHeading: ' +
        payload.heading,
    );
    payload.roll;
    payload.pitch;
    payload.heading;
  });`

**Comment by nkulic** [comment]
Had to re-build

**Comment by dpyeates** [comment]
glad you got it working :-)

**Comment by nkulic** [comment]
> glad you got it working :-)

I did that part but now I wonder why is there no yaw (third axis value)? I can see roll, pitch and heading.

What I would like to achieve is what google maps have for direction beam
![maps-beam-800x420](https://user-images.githubusercontent.com/63425772/116070290-b8250c00-a68c-11eb-8560-271d85bb3013.jpg)

When device is in portrait mode (default), pitch axis can be rotated forward or backwards but degree/heading will remain the same. Whether device screen is facing user, facing floor or facing sky, heading is the same. And same would be for landscape

**Comment by dpyeates** [comment]
What version of React Native?
What device are you using?

Yaw is obtained through payload.heading

When you change for portrait and landscape, remember to set 

Attitude.setRotation('none'); (for portrait)

or Attitude.setRotation('left') or Attitude.setRotation('right') depending on landscape left or right.

**Comment by nkulic** [comment]
@dpyeates I'm using `react-native 0.63.4` and testing sensors on Samsung Galaxy s9+

I have tried and tested in landscape position, and I've set `Attitude.setRotation('left')` and all that changes is **roll** value by 90 degrees (as offset i suppose)

This image can display what I would like to have. If device begin to rotate from portrait mode to landscape, then I would set if statement to check if device is rotated more than 45°. If it is I would switch sensor values so that it fits to landscape mode

![Screenshot_1](https://user-images.githubusercontent.com/63425772/116073331-8f9f1100-a690-11eb-81f3-bac9141f2c66.png)
